# Generated by Django 4.0.2 on 2022-06-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
