# Generated by Django 4.0.2 on 2022-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_ondeploy',
            field=models.URLField(null=True),
        ),
    ]
