# Generated by Django 4.0.2 on 2023-01-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_proudctsize_product_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProudctSize',
            new_name='ProductSize',
        ),
    ]
