# Generated by Django 4.0.2 on 2023-01-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
